export const techCardsItems = [
  {
    name: "Unity Engine",
    description: "C# and Shader Graph",
    imageUrl: "/imgs/logos/unity.svg",
    bgColor: "bg-[#FFFFFF]/15",
  },
  {
    name: "Unreal Engine",
    description: "C++ and Blueprint",
    imageUrl: "/imgs/logos/unreal.svg",
    bgColor: "bg-[#FFFFFF]/15",
  },
  {
    name: "Steamworks",
    description: "Low level Multiplayer, Lobbies and Achievement",
    imageUrl: "/imgs/logos/steam.svg",
    bgColor: "bg-[#00ADEE]/15",
  },
  {
    name: "Google Play",
    description: "Achivements and Version Control",
    imageUrl: "/imgs/logos/google.svg",
    bgColor: "bg-[#008744]/15",
  },
  {
    name: "Git",
    description: "Versionning",
    imageUrl: "/imgs/logos/git.svg",
    bgColor: "bg-[#F1502F]/15",
  },
  {
    name: "SFML",
    description: "C++",
    imageUrl: "/imgs/logos/sfml.svg",
    bgColor: "bg-[#90cd43]/15",
  },
  {
    name: "Raylib",
    description: "C and C++",
    imageUrl: "/imgs/logos/raylib.svg",
    bgColor: "bg-[#FFFFFF]/90",
  },
  {
    name: "Enet",
    description: "C# and C++ UDP networking library",
    imageUrl: "/imgs/logos/networking.svg",
    bgColor: "bg-[#FFFFFF]/90",
  }
];

export const portfolioProjects = [
    {
      id: "quantic",
      heading: "Quantictactoe",
      subheading: "",
      imageUrl: "https://i.imgur.com/7NQ9qRK.png",
      techStack: [
        "Steamworks",
        "Unity",
        "Online Multiplayer",
        "Reflexion Game",
      ],
      liveDemoUrl: "",
      videoUrl: "https://www.youtube.com/embed/7jc1ONhnvX0?si=sBAne5ITG27x8XpN?rel=0",
      videoGameplayUrl: "https://www.youtube.com/embed/7jc1ONhnvX0?si=sBAne5ITG27x8XpN?rel=0",
      contentPath: "/content/Quantictactoe.md",
    },
    {
      id: "space",
      heading: "Space Multiplayer",
      subheading: "",
      imageUrl: "https://i.imgur.com/HqrZtYh.png",
      techStack: [
        "Enet",
        "Unity",
        "Online Multiplayer",
        "Space Arena Shooter",
      ],
      liveDemoUrl: "",
      videoUrl: "https://www.youtube.com/embed/3kGJ9-fZxmw?si=avUP_meTnzj9tN7m?rel=0",
      videoGameplayUrl: "https://www.youtube.com/embed/3kGJ9-fZxmw?si=avUP_meTnzj9tN7m?rel=0",
      contentPath: "/content/Space.md",
    },
    {
      id: "paco",
      heading: "Paco's Anatomy",
      subheading: "",
      imageUrl: "https://i.imgur.com/WjkC0Nw.png",
      techStack: [
        "Alternative Controller",
        "Unity",
        "GDC 2025 Nominee"
      ],
      liveDemoUrl: "",
      videoUrl: "https://www.youtube.com/embed/7jc1ONhnvX0?si=sBAne5ITG27x8XpN?rel=0",
      videoGameplayUrl: "https://www.youtube.com/embed/7jc1ONhnvX0?si=sBAne5ITG27x8XpN?rel=0",
      contentPath: "/content/Paco.md",
    },
    {
    id: "twice",
    heading: "Twice Upon a Time",
    subheading: "",
    imageUrl: "/imgs/projects/portfolio-mockup1.gif",
    techStack: [
      "Unity",
      "C#",
      "Local Multiplayer",
      "Narrative",
      "Platformer",
    ],
    liveDemoUrl: "https://thomasboeglin.itch.io/twice-upon-a-time",
    videoUrl: "https://www.youtube.com/embed/TZRwV7C3Y18?rel=0",
    videoGameplayUrl: "https://www.youtube.com/embed/TZRwV7C3Y18?rel=0",
    contentPath: "/content/Twice.md",
  },
  {
    id: "heal",
    heading: "Heal 'Em Up",
    subheading: "",
    imageUrl: "/imgs/projects/Heal.jpg",
    techStack: [
      "Unity",
      "Google Play",
      "C#",
      "Mobile",
      "Card Game",
      "Turnbased",
    ],
    liveDemoUrl: "https://play.google.com/store/apps/details?id=com.Team8.HealEMUp&hl=fr",
    videoUrl: "https://www.youtube.com/embed/TOMXh5y_iCg?rel=0",
    videoGameplayUrl: "https://www.youtube.com/embed/TOMXh5y_iCg?rel=0",
    contentPath: "/content/Heal.md",
  },
  {
    id: "sfml",
    heading: "The Mothership Calls",
    subheading: "",
    imageUrl: "/imgs/projects/Mothership.png",
    techStack: [
      "SFML",
      "C++",
      "Local Multiplayer",
      "Shoot 'Em Up",
    ],
    liveDemoUrl: "https://usofeurasia.itch.io/the-mothership-calls",
    videoUrl: "https://www.youtube.com/embed/WlBDnu0Lm2w?rel=0",
    videoGameplayUrl: "https://www.youtube.com/embed/WlBDnu0Lm2w?rel=0",
    contentPath: "/content/Ship.md",
  },
  {
    id: "jamo",
    heading: "Super JAM Bros",
    subheading: "",
    imageUrl: "/imgs/projects/Jamo.png",
    techStack: [
      "Unreal Engine",
      "C++",
      "Local Multiplayer",
      "Fighting Game",
      "Super Smash Bros Like",
    ],
    liveDemoUrl: "",
    videoUrl: "/video/Jamo.mp4",
    videoGameplayUrl: "/video/Jamo.mp4",
    contentPath: "/content/Unreal.md",
  },
  {
    id: "camera",
    heading: "Dynamic Camera System",
    subheading: "",
    imageUrl: "/imgs/projects/Bezier.PNG",
    techStack: [
      "Unity",
      "C#",
      "Camera",
      "TPS",
    ],
    liveDemoUrl: "",
    videoUrl: "/video/Camera.mp4",
    videoGameplayUrl: "/video/Camera.mp4",
    contentPath: "/content/Camera.md",
  },
  {
    id: "rast",
    heading: "C++ Rasterizer",
    subheading: "",
    imageUrl: "/imgs/projects/Raz.png",
    techStack: [
      "C++",
      "OpenGL",
      "Rendering",
    ],
    liveDemoUrl: "",
    videoUrl: "/video/Rasterizer.mp4",
    videoGameplayUrl: "/video/Rasterizer.mp4",
    contentPath: "/content/Raz.md",
  },
  {
    id: "cript",
    heading: "The Cryptic Mutation Conundrum",
    subheading: "",
    imageUrl: "/imgs/projects/Cript.png",
    techStack: [
      "Unreal Engine",
      "Blueprint",
      "Horror",
      "Escape Game",
    ],
    liveDemoUrl: "https://zukkinioni.itch.io/tcmc",
    videoUrl: "https://www.youtube.com/embed/Z7_DwYu2pBg?si=p81MlH4zgNv0AH0s",
    videoGameplayUrl: "https://www.youtube.com/embed/Z7_DwYu2pBg?si=p81MlH4zgNv0AH0s",
    contentPath: "/content/Crypt.md",
  }
];

export const testimonialItems = [

];